project:
  type: website

website:
  title: "Foundations of Python"
  navbar:
    left:
      - href: ./index.qmd
        text: Home
      - href: schedule.qmd
        text: Course Schedule
      - href: required_software.qmd
        text: Required Software
      - href: challenge.qmd
        text: "Challenge"
      - href: resources.qmd
        text: "Resources"

editor: 
  render-on-save: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
