project:
  type: website

website:
  title: "SDI Foundations of Python Website"
  navbar:
    left:
      - href: ./index.qmd
        text: Home
      - href: schedule.qmd
        text: Course Schedule
      - href: required_software.qmd
        text: Required Software

editor: 
  render-on-save: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
